---
- name: Migrate Database
  shell: ". /etc/profile.d/rbenv.sh && rake -f {{ prod_site_dir | realpath }}/Rakefile db:migrate"
  args:
    chdir: "{{ prod_site_dir | realpath }}"
  environment: "{{ env_vars | default({}) }}"
  register: migrate_result
  changed_when: migrate_result.stdout is defined and migrate_result.stdout != ""

- name: Compile Assets
  shell: ". /etc/profile.d/rbenv.sh && rake -f {{ prod_site_dir | realpath }}/Rakefile assets:precompile"
  args:
    chdir: "{{ prod_site_dir | realpath }}"
  environment: "{{ env_vars | default({}) }}"
  register: assets_result
  changed_when: assets_result.stdout is defined and assets_result.stdout != ""
