---
- name: Add HHVM apt Key
  apt_key: keyserver=keyserver.ubuntu.com id=0x5a16e7281be7a449 state=present
  sudo: yes

- name: Add HHVM apt Repository
  apt_repository:
    repo: "deb http://dl.hhvm.com/ubuntu trusty-lts-3.9 main"
    state: present
  sudo: yes

- name: Install HHVM
  apt: package=hhvm state=present
  sudo: yes
  notify: Restart HHVM

- name: Start HHVM on Boot
  service: name=hhvm enabled=yes
  sudo: yes
