---
- name: Create MySQL Administrator
  hosts: development-vm

  vars_files:
    - "{{ 'ansible/vars/local_paths.yml' | realpath }}"

  pre_tasks:
    - import_tasks: "{{ tasks_dir }}/prompt/database/user.yml"
      tags: silent

  roles:
    - bbatsche.MySQL
