---
- name: Create MySQL Administrator
  hosts: vagrant
  remote_user: vagrant

  vars:
    mysql_user_priv: "*.*:ALL,GRANT"
  vars_prompt:
    - name:    new_mysql_user
      prompt:  New MySQL Admin
      private: no
    - name:    new_mysql_pass
      prompt:  New Admin Password
      private: yes
      confirm: yes

  roles:
    - MySQL-Install
    - MySQL
