---
- name: Create MySQL Readonly User
  hosts: development-vm

  vars_files:
    - "{{ 'ansible/vars/local_paths.yml' | realpath }}"

  pre_tasks:
    - import_tasks: "{{ tasks_dir }}/prompt/database/user.yml"
      tags: silent
    - import_tasks: "{{ tasks_dir }}/prompt/database/database.yml"
      tags: silent

    - set_fact:
        new_db_priv: "{{ new_db_name + '.*:SELECT' if new_db_name is defined else '*.*:SELECT' }}"
      tags: silent

  roles:
    - bbatsche.MySQL
