---
- name: Create MySQL Readonly User
  hosts: development-vm

  pre_tasks:
    - import_tasks: ../../../tasks/prompt/database/user.yml
      tags: silent
    - import_tasks: ../../../tasks/prompt/database/database.yml
      tags: silent

    - set_fact:
        new_db_priv: "{{ new_db_name + '.*:SELECT' if new_db_name is defined else '*.*:SELECT' }}"
      tags: silent

  roles:
    - bbatsche.MySQL
