---
app_env: prod

www_home: /srv/www

mongodb_admin:  "{{ lookup('env', 'USER') }}"
mysql_admin:    "{{ lookup('env', 'USER') }}"
postgres_admin: "{{ lookup('env', 'USER') }}"

git_home: /var/git
git_remote: production

ruby_version: 2.2.3

ansible_python_interpreter: /usr/bin/python2
