---
env_name: dev

http_root: /vagrant/sites

# This is already set by default within the various DB roles
# However, we need to set it out here so that our preflight checks work
db_admin: vagrant

# Required vars for Phpenv role
xdebug_version: 2.6.0

composer_packages:
  - name: psy/psysh
    version: ^0.8
  - name: hirak/prestissimo
    version: ^0.3
  - name: phpunit/phpunit
    version: ^6.5
  - name: phpspec/phpspec
    version: ^4.3

install_mariadb: yes
install_postgres: yes

postgres_enable_network: yes
