---
env_name: dev

http_root: /vagrant/sites

# This is already set by default within the various DB roles
# However, we need to set it out here so that our preflight checks work
db_admin: vagrant

# Required vars for Phpenv role
xdebug_version: 2.5.5

default_packages:
  - name: psy/psysh
    version: ^0.8

php5_packages:
  - name: phpunit/phpunit
    version: ^5.7
  - name: phpspec/phpspec
    version: ^3.4

php7_packages:
  - name: phpunit/phpunit
    version: ^6.5
  - name: phpspec/phpspec
    version: ^4.3
