---
env_name: dev

http_root: /vagrant/sites

# This is already set by default within the various DB roles
# However, we need to set it out here so that our preflight checks work
db_admin: vagrant

# Required vars for Phpenv role
xdebug_version: 2.7.2

composer_packages:
  - name: psy/psysh
    version: ^0.9
  - name: hirak/prestissimo
    version: ^0.3
  - name: phpunit/phpunit
    version: ^6.5
  - name: phpspec/phpspec
    version: ^5.1
  - name: localheinz/composer-normalize
    version: ^1.1

content_security_policy:
  "default-src":
    - self
  "script-src":
    - self
    - unsafe-inline
  "style-src":
    - self
    - unsafe-inline
  "base-uri": []
  "form-action":
    - self
  "frame-ancestors": []
  "upgrade-insecure-requests": yes

install_mariadb: yes
install_postgres: yes

postgres_enable_network: yes

ntp_enabled: no
ntp_timezone: America/Chicago

mariadb_apt_mirror: http://ftp.utexas.edu/

domain_tld: test
