---
env_name: dev

http_root: /vagrant/sites

# This is already set by default within the various DB roles
# However, we need to set it out here so that our preflight checks work
db_admin: vagrant

# Required vars for Phpenv role
xdebug_version: 2.4.0
phpunit_version: ~5.3
