---
app_env: dev

mongodb_admin: vagrant
mongodb_pass:  vagrant

mysql_admin: vagrant
mysql_pass:  vagrant

postgres_admin: vagrant
postgres_pass:  vagrant

ansible_python_interpreter: /usr/bin/python2
