---
- name: Initialize Production Server
  hosts: production
  remote_user: root

  vars_prompt:
    - name:    ansible_sudo_pass # When Ansible 2 comes out, convert this to use password_hash filter, confirm not empty
      prompt:  Sudo Password
      private: yes
      confirm: yes
      encrypt: md5_crypt
      salt_size: 7
    - name:    admin_email
      prompt:  eMail Address for Notifications
      private: no

  vars:
    console_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: Production server must be Ubuntu
      assert:
        that: ansible_distribution == "Ubuntu"
    - name: Production server must be Trusty Tahr
      assert:
        that: ansible_distribution_version == "14.04"

  roles:
    - production
    - common
