---
- name: Initialize Vagrant Box
  hosts: vagrant
  remote_user: vagrant

  roles:
    - common

  handlers:
    - name: Restart Server
      debug: msg="Run 'vagrant reload' after provisioning completes"
