---
- name: Create MongoDB Database
  hosts: vagrant
  remote_user: vagrant

  vars:
    mongodb_roles: dbOwner
  vars_prompt:
    - name:    db_name
      prompt:  Database Name (e.g. something_db)
      private: no
    - name:    new_mongodb_user
      prompt:  Database Owner (e.g. something_user)
      private: no
    - name:    new_mongodb_pass
      prompt:  Password for Database Owner
      private: yes
      confirm: yes

  roles:
    - MongoDB
