---
- name: Create HipHop VM Site
  hosts: vagrant
  remote_user: vagrant

  vars_prompt:
    - name: domain
      prompt: "New Domain Name (e.g. codeup.dev)"
      private: no

  roles:
    - ../../../ansible/roles/hhvm
