---
- name: Create Dynamic PHP Site
  hosts: vagrant
  remote_user: vagrant

  vars:
    dynamic_php: yes
  vars_prompt:
    - name: domain
      prompt: "New Domain Name (e.g. codeup.dev)"
      private: no

  pre_tasks:
    - name: Development domains must end with .dev
      assert:
        that: "domain.endswith('.dev')"

  roles:
    - php
