---
- name: Create Python Site
  hosts: vagrant
  remote_user: vagrant

  vars_prompt:
    - name: domain
      prompt: "New Domain Name (e.g. codeup.dev)"
      private: no

  pre_tasks:
    - name: Development domains must end with .dev
      assert:
        that: domain.endswith(".dev")

  roles:
    - Python
