---
- include: dot-env-php.yml
  when: site_type == "laravel4"

- name: Add Environment Values to Config
  lineinfile:
    dest: /etc/nginx/sites-available/{{ production_domain }}
    insertafter: ^\s*include\s+fastcgi.conf
    regexp: ^\s*fastcgi_param\s+{{ item.key }}
    line: fastcgi_param {{ item.key }} {{ item.value }};
    create: no
  with_dict: "{{ env_vars | default({}) }}"
  notify: Reload Nginx Config

- name: Install Composer Dependencies
  composer: working_dir={{ prod_site_dir | realpath }} no_dev=yes optimize_autoloader=yes

- include: laravel.yml
  when: site_type in ["laravel4", "laravel5", "lumen"]
