---
- hosts: development-vm
  gather_facts: no

  vars_prompt:
  - name:    new_db_user
    prompt:  Database User (e.g. something_user)
    private: no

  - name:    new_db_pass
    prompt:  Password for Database User
    private: yes
    confirm: yes

  pre_tasks:
    - name: Password cannot be blank
      assert:
        that: new_db_pass != ''

    - name: Cannot modify DB admin
      assert:
        that: new_db_user != db_admin

    - set_fact: new_db_user={{ new_db_user }} new_db_pass={{ new_db_pass }}
