---
- hosts: development-vm
  gather_facts: no

  vars_prompt:
  - name:    domain
    prompt:  Domain Name (e.g. domain.name.test)
    private: no

  pre_tasks:
    - block:
      - name: Check for email var file
        local_action: stat path=../../../hosts/group_vars/_email.yml
        register: email_var_file
      - include_vars: ../../../hosts/group_vars/_email.yml
        when: email_var_file.stat.exists
      when: email_address is not defined
    
    - block:
      - pause:
          prompt: Email Address
        register: email_prompt
      - set_fact: email_address={{ email_prompt.user_input }}
      when: email_address is not defined
      
    - name: Clean domain name
      set_fact: "domain={{ domain | trim | lower }}"

    - name: Domains must be made of alphanumeric characters
      assert:
        that: "domain | search('^[a-z0-9][a-z0-9\\-.]+[a-z0-9]$')"

    - name: Development domains must end with .test
      assert:
        that: domain.endswith(".test")

    - set_fact: domain={{ domain }}
