---
- name: Create MySQL Administrator
  hosts: vagrant
  remote_user: vagrant

  vars:
    app_env: dev # move this into a host var
    mysql_user_priv: "*.*:ALL,GRANT"
  vars_prompt:
    - name: new_mysql_user
      prompt: "New MySQL Username"
      private: no
    - name: new_mysql_pass
      prompt: "New User Password"
      private: yes
      confirm: yes

  roles:
    - MySQL
