---
- name: Create MySQL Database
  hosts: vagrant
  remote_user: vagrant

  vars:
    ansible_dir: ../../../ansible
  vars_files:
    - "{{ ansible_dir }}/host_vars/vagrant.yml"
  vars_prompt:
    - name: db_name
      prompt: "MySQL Database Name (e.g. something_db)"
      private: no
    - name: new_mysql_user
      prompt: "Database Owner (e.g. something_user)"
      private: no
    - name: new_mysql_pass
      prompt: "Owner Password"
      private: yes
      confirm: yes

  tasks:
    - name: Create MySQL Database
      mysql_db:
        name:           "{{ db_name }}"
        login_user:     "{{ mysql_admin }}"
        login_password: "{{ mysql_pass }}"
        collation:      utf8_general_ci
        state:          present

    - name: Create MySQL User for Database
      mysql_user:
        name:           "{{ new_mysql_user }}"
        password:       "{{ new_mysql_pass }}"
        login_user:     "{{ mysql_admin }}"
        login_password: "{{ mysql_pass }}"
        priv:           "{{ db_name }}.*:ALL"
        state:          present
