---
- name: Create MySQL Database
  hosts: vagrant
  remote_user: vagrant

  vars:
    app_env: dev # move this into a host var
  vars_prompt:
    - name: db_name
      prompt: "MySQL Database Name (e.g. something_db)"
      private: no
    - name: new_mysql_user
      prompt: "Database Owner (e.g. something_user)"
      private: no
    - name: new_mysql_pass
      prompt: "Owner Password"
      private: yes
      confirm: yes

  pre_tasks:
    - name: Generate Database Privileges
      set_fact:
        mysql_user_priv: "{{ db_name }}.*:ALL"

  roles:
    - MySQL
