---
- import_playbook: ../_prompts/domain.yml

- name: Create Magento 2 Site
  hosts: development-vm

  vars:
    dynamic_php: yes
    public_directory: pub
    php_max_execution_time: 300
    nginx_configs:
      - magento-{{ domain }}.conf

  roles:
  - role: bbatsche.PHP

  tasks:
    - name: Copy Magento Nginx Config
      template:
        src: ../../../templates/magento.conf.j2
        dest: /etc/nginx/conf.d/magento-{{ domain }}.conf
      become: yes
      notify: Restart Nginx

    - name: Install RabbitMQ
      apt: name=rabbitmq-server state=present
      become: yes

- import_playbook: ../_post_php_site.yml
