---
- import_playbook: ../_prompts/domain.yml

- name: Create Magento 2 Site
  hosts: development-vm

  vars:
    dynamic_php: yes
    public_directory: pub
    php_max_execution_time: 300
    nginx_configs:
      - php-{{ domain }}.conf
      - magento.conf

  roles:
  - role: bbatsche.PHP

  tasks:
    - name: Copy Magento Nginx Config
      copy: src=../../../files/magento.conf dest=/etc/nginx/conf.d/magento.conf
      become: yes
      notify: Restart Nginx

    - name: Install RabbitMQ
      apt: name=rabbitmq-server state=present
      become: yes

- import_playbook: ../_post_php_site.yml
