---
- include: ../_prompts/domain.yml

- name: Create Dynamic PHP 5.6 Site
  hosts: development-vm

  roles:
  - role: bbatsche.Phpenv

    dynamic_php: yes

    php_version:      5.6.21
    xdebug_version:   2.4.0
    phpunit_version: ~5.3

    pecl_extensions:
    - name: yaml
      version: 1.2.0

    - name: imagick
      version: 3.4.1

    - name: redis
      version: 2.2.7
