---
- name: Create Python 2.7 Site
  hosts: development-vm

  vars_files:
    - "{{ 'ansible/vars/local_paths.yml' | realpath }}"

  pre_tasks:
    - import_tasks: "{{ tasks_dir }}/import_vars.yml"
      tags: silent
    - import_tasks: "{{ tasks_dir }}/prompt/email.yml"
      tags: silent
    - import_tasks: "{{ tasks_dir }}/prompt/domain.yml"
      tags: silent

  roles:
    - role: bbatsche.Python
      python_version: 2.7

  post_tasks:
    - import_tasks: "{{ tasks_dir }}/post_ssl_dev_site.yml"
