---
- name: Create Python 3.4 Site
  hosts: development-vm

  pre_tasks:
    - import_tasks: ../../../tasks/import_vars.yml
      tags: silent
    - import_tasks: ../../../tasks/prompt/email.yml
      tags: silent
    - import_tasks: ../../../tasks/prompt/domain.yml
      tags: silent

  roles:
    - role: bbatsche.Python
      python_version: 3.4

  post_tasks:
    - import_tasks: ../../../tasks/post_ssl_dev_site.yml
