---
- include: ../_prompts/domain.yml

- name: Create Static PHP 7 Site
  hosts: development-vm

  roles:
  - role: bbatsche.Phpenv

    dynamic_php: no

    php_version: 7.0.6

    pecl_extensions: "{{ default_pecl_extensions + php7_extensions }}"
