---
- include: ../_prompts/domain.yml

- name: Create Static PHP 5.6 Site
  hosts: development-vm

  roles:
  - role: bbatsche.PHP

    dynamic_php: no

    php_version: 5.6.21

    pecl_extensions: "{{ default_pecl_extensions + php5_extensions }}"

- include: ../_post_php_site.yml
