---
- import_playbook: ../_prompts/domain.yml

- name: Create Static PHP 7 Site
  hosts: development-vm

  vars:
    dynamic_php: no

  roles:
  - role: bbatsche.PHP

- import_playbook: ../_post_php_site.yml
