---
- name: Create Static PHP 7 Site
  hosts: development-vm

  vars:
    dynamic_php: no

  pre_tasks:
    - import_tasks: ../../../tasks/import_vars.yml
      tags: silent
    - import_tasks: ../../../tasks/prompt/email.yml
      tags: silent
    - import_tasks: ../../../tasks/prompt/domain.yml
      tags: silent

  roles:
    - role: bbatsche.PHP

  post_tasks:
    - import_tasks: ../../../tasks/post_php_site.yml
