---
- include: ../_prompts/domain.yml

- name: Create Static PHP 5.6 Site
  hosts: development-vm

  vars:
    dynamic_php: no
    php_version: 5.6.24

  roles:
  - role: bbatsche.PHP
    pecl_extensions: "{{ default_pecl_extensions + php5_extensions }}"

- include: ../_post_php_site.yml
