---
# Really don't understand why this service task must be written as a command. Maybe a bug??
- name: Reload Nginx Config
  command: sudo /usr/sbin/service nginx reload

- name: Restart App
  file: name={{ prod_site_dir | realpath }}/tmp/restart.txt state=touch
