---
- name: Install
  apt: package={{ item }} state=present
  sudo: yes
  with_items:
    - mysql-server
    - percona-toolkit
  register: mysql_install

- name: Create Configuration File
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  sudo: yes
  notify: Restart

- include: lockdown.yml
  when: mysql_install | changed

- include: database.yml
  when: db_name is defined

- include: user.yml
  when: new_mysql_user is defined
