---
- name: Create User
  mysql_user:
    name:           "{{ new_mysql_user }}"
    password:       "{{ new_mysql_pass }}"
    login_user:     "{{ mysql_admin | default('root') }}"
    login_password: "{{ mysql_pass  | default(omit) }}"
    priv:           "{{ mysql_user_priv }}"
    state:          present
