---
# Node.js
- name: Check for Node Dependencies
  stat: path={{ prod_site_dir | realpath }}/package.json
  register: package_file

- name: Read Node Dependencies
  command: cat {{ prod_site_dir | realpath }}/package.json
  register: package_content
  when: package_file.stat.exists
  changed_when: false

- name: Install Node Dependencies
  npm: path={{ prod_site_dir | realpath }} global=no production=yes
  when: package_file.stat.exists
  register: node_install

# Bower
- name: Check for Bower Dependencies
  stat: path={{ prod_site_dir | realpath }}/bower.json
  register: bower_dependencies

- name: Install Bower Dependencies
  bower: path={{ prod_site_dir | realpath }}
  when: bower_dependencies.stat.exists
  register: bower_install

# Grunt
- name: Check for Grunt File
  stat: path={{ prod_site_dir | realpath }}/Gruntfile.js
  register: grunt_file

- name: Run Default Grunt Task
  command: /usr/local/bin/grunt --gruntfile={{ prod_site_dir | realpath }}/Gruntfile.js --base={{ prod_site_dir | realpath }}
  when: grunt_file.stat.exists and (git_push.changed or node_install.changed or bower_install.changed)

# Gulp
- name: Check for Gulp File
  stat: path={{ prod_site_dir | realpath }}/gulpfile.js
  register: gulp_file

- name: Run Default Gulp Task
  command: /usr/local/bin/gulp --gulpfile {{ prod_site_dir | realpath }}/gulpfile.js --cwd {{ prod_site_dir | realpath }}
  when: gulp_file.stat.exists and (git_push.changed or node_install.changed or bower_install.changed)
