---
# test mail with the following command:
# echo "Mail test." | mail -s "Just Testing" <some_email@address>

- name: Set up Postfix Selections (main mailer type)
  command: 'echo "{{ item }}" | debconf-set-selections'
  with_items:
    - postfix postfix/main_mailer_type select Internet Site
    - postfix postfix/mailname string localhost
    - postfix postfix/destinations string localhost.localdomain, localhost

- name: Install Postfix
  apt: pkg=postfix state=present

- name: Set Postfix to Loopback Only
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: "^inet_interfaces"
    line:   "inet_interfaces = loopback-only"
    state:  present
  notify: Restart Postfix

- name: Set Postfix Hostname
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: "^myhostname"
    line:   "myhostname = {{ ansible_fqdn }}"
    state:  present
  notify: Restart Postfix

- name: Create root eMail Alias
  lineinfile:
    dest:   /etc/aliases
    regexp: "^root"
    line:   "root: {{ admin_email }}"
    state:  present
  notify: Restart Postfix
