---
- name: Remove MySQL Root User
  mysql_user:
    name:           root
    host:           "{{ item }}"
    login_user:     "{{ mysql_admin }}"
    login_password: "{{ mysql_pass }}"
    state:          absent
  when: not mysql_dev
  with_items:
    - localhost
    - 127.0.0.1
    - "::1"
    - "{{ ansible_hostname }}"
