---
- name: Install PHP
  apt: package={{ item }} state=present
  sudo: yes
  with_items:
    - php5
    - php5-cli
    - php5-json
    - php5-mysql
    - php5-pgsql
    - php5-redis
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-imagick
    - php5-fpm
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

- name: Install PHP Xdebug
  apt: package=php5-xdebug state=present
  when: app_env == "dev"
  sudo: yes
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

# Ubuntu 13.10+ has a bug in where the mcrypt ini file is placed.
# Work around those by copying the file to the proper location and enabling mcrypt.
- name: Copy mcrypt Config to Proper Location and Enable
  command: php5enmod mcrypt creates=/etc/php5/fpm/conf.d/20-mcrypt.ini
  sudo: yes
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

- name: Remove Default PHP-FPM Pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  sudo: yes
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

- name: Create PHP-FPM Log Directory
  file: path=/var/log/php-fpm state=directory owner=www-data
  sudo: yes

- name: Create PHP Log Directory
  file: path=/var/log/php state=directory owner=www-data
  sudo: yes

- name: Set PHP-FPM Error Log Path
  lineinfile:
    dest:   /etc/php5/fpm/php-fpm.conf
    state:  present
    regexp: ^error_log\s?=
    line:   error_log = /var/log/php-fpm/error.log
  sudo: yes
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

- name: Delete old PHP-FPM Log
  file: path=/var/log/php5-fpm.log state=absent
  sudo: yes

- name: Create PHP Session Directory
  file: path=/var/lib/php/session state=directory owner=www-data
  sudo: yes

- name: Modify php.ini Settings
  template: src=php.ini.j2 dest=/etc/php5/{{ item }}/php.ini
  sudo: yes
  with_items:
    - fpm
    - cli
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

- name: Check for Composer
  stat: path=/usr/local/bin/composer
  register: composer_result

- name: Download Composer Installer
  get_url: url=https://getcomposer.org/installer dest=/tmp/install-composer.php
  when: composer_result.stat.exists == false

- name: Install Composer
  command: >
    php /tmp/install-composer.php --install-dir=/usr/local/bin --filename=composer
    creates=/usr/local/bin/composer
  sudo: yes

- name: Add Composer's Bin to $PATH
  lineinfile:
    dest: ~/.bashrc
    line: 'export PATH="$HOME/.composer/vendor/bin:$PATH"'
    state: present
