---
- name: Create PostgreSQL Administrator
  postgresql_user:
    name:            "{{ new_postgres_user }}"
    password:        "{{ new_postgres_pass }}"
    state:           present
    role_attr_flags: SUPERUSER,CREATEDB
  sudo: yes
  sudo_user: postgres

- name: Disable Login for PostgreSQL Default User
  postgresql_user:
    name:            postgres
    role_attr_flags: NOLOGIN
  sudo: yes
  sudo_user: postgres

- name: Password Authentication for All PostgreSQL Users
  lineinfile:
    name: /etc/postgresql/9.3/main/pg_hba.conf
    regexp: (local\s+all\s+{{ item }}\s+)peer
    line: \1md5
    state: present
    backrefs: yes
  with_items:
    - postgres
    - all
  sudo: yes
  notify: Restart PostgreSQL
