---
- name: Create PostgreSQL Administrator (sudo)
  postgresql_user:
    name:           "{{ new_postgres_user }}"
    password:       "{{ new_postgres_pass }}"
    state:          present
    role_attr_flags: SUPERUSER
  sudo: yes
  sudo_user: postgres
  register: postgres_admin_sudo
  failed_when: postgres_admin_sudo.msg is defined and "no password supplied" not in postgres_admin_sudo.msg

- name: Create PostgreSQL Administrator (admin user)
  postgresql_user:
    name:           "{{ new_postgres_user }}"
    password:       "{{ new_postgres_pass }}"
    login_user:     "{{ postgres_admin | default('postgres') }}"
    login_password: "{{ postgres_pass | default(omit) }}"
    state:          present
    role_attr_flags: SUPERUSER
  when: postgres_admin_sudo.msg is defined and "no password supplied" in postgres_admin_sudo.msg

- name: Create PostgreSQL Admin Database
  postgresql_db:
    name:           "{{ new_postgres_user }}"
    login_user:     "{{ postgres_admin  | default('postgres') }}"
    login_password: "{{ postgres_pass | default(omit) }}"
    owner:          "{{ new_postgres_user }}"
    state:          present
