---
- name: Create PostgreSQL User
  postgresql_user:
    name:           "{{ db_name }}"
    password:       "{{ new_postgres_pass }}"
    encrypted:      yes
    login_user:     "{{ postgres_admin | default('postgres') }}"
    login_password: "{{ postgres_pass | default(omit) }}"
    state:          present

- name: Create PostgreSQL Database
  postgresql_db:
    name:           "{{ db_name }}"
    login_user:     "{{ postgres_admin | default('postgres') }}"
    login_password: "{{ postgres_pass | default(omit) }}"
    owner:          "{{ db_name }}"
    state:          present
