---
- name: Install System Ruby
  apt: package=ruby2.0 state=present
  sudo: yes

- name: Install Rbenv
  apt: package=rbenv state=present
  sudo: yes

- name: Install Rbenv Plugins
  git:
    repo: https://github.com/sstephenson/{{ item }}.git
    dest: /usr/local/rbenv/plugins/{{ item }}/
  sudo: yes
  notify: Rehash Rbenv
  with_items:
    - ruby-build
    - rbenv-vars
    - rbenv-gem-rehash
    - rbenv-default-gems

- name: Install Binstubs
  git:
    repo: https://github.com/ianheggie/rbenv-binstubs.git
    dest: /usr/local/rbenv/plugins/rbenv-binstubs/
    version: v1.4
  sudo: yes
  notify: Rehash Rbenv

- name: Add Rbenv to Profile
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh
  sudo: yes

- name: Install Rack
  gem: name=rack user_install=no state=present
  notify: Rehash Rbenv
  sudo: yes
