---
- name: Install Rbenv
  apt: package=rbenv state=present
  sudo: yes

- name: Install Rbenv Plugins
  git:
    repo: https://github.com/sstephenson/{{ item }}.git
    dest: ~/.rbenv/plugins/{{ item }}/
  with_items:
    - ruby-build
    - rbenv-vars
    - rbenv-gem-rehash
    - rbenv-default-gems

- name: Add Rbenv's Bin to $PATH
  lineinfile:
    dest: ~/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present

- name: Add Rbenv Init to Bash
  lineinfile:
    dest: ~/.bashrc
    line: 'eval "$(rbenv init -)"'
    state: present

- name: Install Ruby
  command: rbenv install {{ ruby_version }} creates=~/.rbenv/versions/2.2.2

- name: Set Global Ruby Version
  copy:
    content: '{{ ruby_version }}\n'
    dest:    ~/.rbenv/version
