---
- name: Install Rbenv
  apt: package=rbenv state=present
  sudo: yes

- name: Install Rbenv Plugins
  git:
    repo: https://github.com/sstephenson/{{ item }}.git
    dest: /usr/local/rbenv/plugins/{{ item }}/
  sudo: yes
  with_items:
    - ruby-build
    - rbenv-vars
    - rbenv-gem-rehash
    - rbenv-default-gems

- name: Install Ruby
  command: rbenv install {{ ruby_version }} creates=/usr/local/rbenv/versions/{{ ruby_version }}
  environment:
    RBENV_ROOT: /usr/local/rbenv
  sudo: yes

- name: Set Global Ruby Version
  copy:
    content: '{{ ruby_version }}\n'
    dest:    /usr/local/rbenv/version
  sudo: yes

- name: Add Rbenv to Profile
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh
  sudo: yes
