---
- name: Install NVM
  git:
    repo: https://github.com/creationix/nvm.git
    dest: /usr/local/nvm
    version: "{{ nvm_version }}"
  sudo: yes

- name: Add NVM to Profile
  copy: src=nvm.sh dest=/etc/profile.d/nvm.sh
  sudo: yes

- name: Create NVM Directories
  file: path=/usr/local/nvm/{{ item }} state=directory owner={{ ansible_ssh_user }} mode=0775
  with_items:
    - alias
    - bin
    - src
    - versions
  sudo: yes

- name: Install Current Version
  shell: . /usr/local/nvm/nvm.sh && nvm install {{ node_version }}
  args:
    creates: /usr/local/nvm/versions/node/{{ node_version }}
  environment:
    NVM_DIR: /usr/local/nvm
  sudo: yes
