---
- name: Create PostgreSQL Administrator
  hosts: vagrant
  remote_user: vagrant

  vars:
    role_attr: SUPERUSER
  vars_prompt:
    - name: new_postgres_user
      prompt: "New PostgreSQL Username"
      private: no
    - name: new_postgres_pass
      prompt: "New User Password"
      private: yes
      confirm: yes

  roles:
    - PostgreSQL
