---
- name: Create PostgreSQL Database
  hosts: vagrant
  remote_user: vagrant

  vars:
    ansible_dir: ../../../ansible
  vars_files:
    - "{{ ansible_dir }}/host_vars/vagrant.yml"
  vars_prompt:
    - name: db_name
      prompt: "PostgreSQL Database Name"
      private: no
    - name: new_postgres_pass
      prompt: "PostgreSQL Database Owner Password"
      private: yes
      confirm: yes

  tasks:
    - name: Create PostgreSQL User
      postgresql_user:
        name:           "{{ db_name }}"
        password:       "{{ new_postgres_pass }}"
        encrypted:      yes
        login_user:     "{{ postgres_admin | default('postgres') }}"
        login_password: "{{ postgres_pass | default(omit) }}"
        state:          present

    - name: Create PostgreSQL Database
      postgresql_db:
        name:           "{{ db_name }}"
        login_user:     "{{ postgres_admin | default('postgres') }}"
        login_password: "{{ postgres_pass | default(omit) }}"
        owner:          "{{ db_name }}"
        state:          present
