---
- name: Create PostgreSQL Database
  hosts: development-vm

  vars_files:
    - "{{ 'ansible/vars/local_paths.yml' | realpath }}"

  pre_tasks:
    - import_tasks: "{{ tasks_dir }}/prompt/database/database.yml"
      tags: silent
    - import_tasks: "{{ tasks_dir }}/prompt/database/user.yml"
      tags: silent

    - assert:
        that: new_db_name is defined
        msg: Database name is required
      tags: silent

  roles:
    - bbatsche.PostgreSQL
