---
- hosts: development-vm
  gather_facts: no

  vars_prompt:
  - name:    domain
    prompt:  Domain Name (e.g. domain.name.test)
    private: no

  pre_tasks:
    - name: Clean domain name
      set_fact: "domain={{ domain | trim | lower }}"

    - name: Domains must be made of alphanumeric characters
      assert:
        that: "domain | search('^[a-z0-9][a-z0-9\\-.]+[a-z0-9]$')"

    - name: Development domains must end with .test
      assert:
        that: domain.endswith(".test")

    - set_fact: domain={{ domain }}
