---
- name: Create User
  postgresql_user:
    name:           "{{ new_postgres_user }}"
    password:       "{{ new_postgres_pass }}"
    db:             postgres
    encrypted:      yes
    login_user:     "{{ postgres_admin | default('postgres') }}"
    login_password: "{{ postgres_pass  | default(omit) }}"
    state:          present
    role_attr_flags: "{{ role_attr | default(omit) }}"
